name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'tests/**'
      - 'Cargo.*'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Install dependency
        run: sudo apt-get update && sudo apt-get install -y xvfb xsel
      - name: Run test
        run: RUST_BACKTRACE=1 xvfb-run cargo test -- --test-threads=1 --test cb # FIXME